### PR TITLE
ECCI-243: Switch to the new cookie module

### PR DESCRIPTION
**Pull request by MatthewWilkes**
This switches to the LGD cookie module and integrates the patch from PR #100.

### CODE REVIEW

**Comment by MatthewWilkes** [comment]
@AnthonySGeorge @siliconmeadow This has a blocks issue that is somewhat beyond me.

**Review by siliconmeadow — APPROVED** [review]
Works locally for me too.

LGTM

**Comment by MatthewWilkes** [comment]
@AnthonySGeorge I've added https://github.com/essexcountycouncil/essex-intranet-drupal/pull/101/commits/dcdb4f5ab2c085288c1b5840e027529f70eff988 because the spinner was misaligned for me. Can you check you're happy?

**Comment by AnthonySGeorge** [comment]
The animation all looks good however, we've lost the radio button styling

**Comment by MatthewWilkes** [comment]
@AnthonySGeorge Moved the custom CSS into the new module

**Comment by siliconmeadow** [comment]
I need to update composer on this for localgov_base, btw.....

**Review by siliconmeadow — APPROVED** [review]
LGTM. Still looking good. The theming of the radio buttons look ok for me @AnthonySGeorge. I'm not suggesting, however, that the site be hosted from my machine.

**Pull request merged**
