### PR TITLE
ECCI-440: Recreated Curve

### PR DESCRIPTION
**Pull request by AnthonySGeorge**
This adds a curve below the page section when the boolean is selected.

### CODE REVIEW

**Comment by Polynya** [comment]
Added the JIRA ticket to the title

**Comment by kurtisRogers-Nomensa** [comment]
Has a conflict, will approve once resolved

**Comment by AnthonySGeorge** [comment]
> Has a conflict, will approve once resolved

Resolved

**Review by kurtisRogers-Nomensa — APPROVED** [review]
LGTM

**Pull request merged**
