### PR TITLE
ECCI-417: Styles for 1+4 news component on subsite

### PR DESCRIPTION
**Pull request by kemiga**

### CODE REVIEW

**Comment by Polynya** [comment]
Please change the base branch from develop to release/202311 and check if Kurt's changes affect yours

**Comment by kemiga** [comment]
Changed the base branch. Are Kurt's changes in develop?

**Comment by Polynya** [comment]
Kurt's changes are in release/202311 and not in develop yet. Do these commits affect your work?

- https://github.com/essexcountycouncil/essex-intranet-drupal/commit/ff0455d130b664db08cc6f2e24c6616dc13a28e4
- https://github.com/essexcountycouncil/essex-intranet-drupal/commit/ab7562d9637e1b4ed66ee3d2decf87932a685032
- https://github.com/essexcountycouncil/essex-intranet-drupal/commit/2e7c6511c2d1ec06cff8127ca99072a038d0834b

**Comment by kemiga** [comment]
Hmm yes they probably do, and I notice the news card styles have been put into `preliminary.css` and when I spoke to Ant we decided to put all news and news card styles in a separate `news.css` file, so these will have to be moved

**Review by kurtisRogers-Nomensa — APPROVED** [review]
LGTM

**Pull request merged**
